version: "3.7"
services:
  invoice-app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.31
    ports:
      - "32000:3327"
    environment:
      MYSQL_ROOT_PASSWORD: Root1234
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro